### ISSUE TITLE
与前端协商完善账号相关功能的Api

### ISSUE THREAD

**Issue by EdrowsLuo** [DDHelper/DDHelper#2]
- [x] #3
- [x] #4
- [x] #8
- [x] #5
- [x] #6
- [x] #11

**Comment by EdrowsLuo** [comment]
初次迭代以最小功能进行实现，确定了两个api：
/auth/login
/auth/regist

**Comment by EdrowsLuo** [comment]
可参考的项目：https://github.com/liangliangyy/DjangoBlog

**Comment by EdrowsLuo** [comment]
https://learndjango.com/tutorials/django-login-and-logout-tutorial

**Comment by EdrowsLuo** [comment]
> 在写登陆和注册的view的过程中，数据库那边怎么处理呢？没有数据库用户数据的接口，很多地方不太好写，要不我顺便把数据库用户账户模型也简单定义一下，用python自带的sqlite，或者我先直接用django的用户包？ @EdrowsLuo

用户数据和数据库的接口django能够自动处理的，我们只需要在models.py里定义模型就可以了，建议看下文档或者教程：
菜鸟教程：https://www.runoob.com/django/django-model.html
官方文档：https://docs.djangoproject.com/zh-hans/3.2/topics/db/models/
django的提供的默认实现就是通过这个实现的，已经帮我们写好了，如果要做自定义的话可以参考上面我发的那个博客项目

**Comment by nagi2330** [comment]
我提交是直接到add-url branch嘛？ @EdrowsLuo

**Comment by EdrowsLuo** [comment]
> 我提交是直接到add-url branch嘛？ @EdrowsLuo

你写的是什么功能？
